name: autoupdate
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          EXCLUDED_LABELS: "dependencies"
          MERGE_MSG: "Auto-updating branch."
          MERGE_CONFLICT_ACTION: "fail"
