name: Build docker images

on:
  push:
    branches: # At least when doing some tests
     - "**"
    tags:
      - "v*.*.*"
  # pull_request:

jobs:
  build-and-push:
    strategy:
      matrix:
        type: ["", "alpine"]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build & execute
        run: |
          go build -v ./...
          ./ci-info
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: fclairamb/ci-info
          flavor: |
            suffix=${{ matrix.type }}
            suffixLatest=${{ matrix.type }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=alpine
            type=ref,event=branch
            type=ref,event=pr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.type }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: github.repository == 'fclairamb/ci-info'
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: github.repository == 'fclairamb/ci-info'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push (scratch)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile${{ matrix.type != '' && format('.{0}', matrix.type) || '' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: ${{ github.repository == 'fclairamb/ci-info' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  build-and-push-status:
      needs: build-and-push
      runs-on: ubuntu-20.04
      steps:
        - run: echo 'All good'