name: Release # Workflow name displayed on GitHub

on:
  workflow_dispatch: # Trigger manually
    branches: main # Branch on which the workflow will run

jobs:
  new-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2 # Checkout our working repository
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.1
        with:
          github-token: ${{ secrets.github_token }}
          create-summary: true
      - name: Create Release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
